# Generated by Django 2.0.dev20170211211108 on 2017-02-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_price',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('book', 'Book'), ('video', 'Video')], default='video', max_length=64),
        ),
    ]
