# Generated by Django 2.0.dev20170211211108 on 2017-02-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=256)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
