# Generated by Django 2.0.dev20170211211108 on 2017-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_level',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='all', max_length=64),
        ),
    ]
